version: '3.8'

services:
  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # Volume para persistir o banco SQLite
      - sqlite_data:/app/db
    networks:
      - app_network
    environment:
      - DEBUG=1
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--deploy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "5173:5173"  # Porta correta do Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - HOST=0.0.0.0
      - PORT=5173
    depends_on:
      - backend
    networks:
      - app_network
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

  # Nginx (Proxy Reverso - Opcional)
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    profiles:
      - nginx

# Volumes para persistência de dados
volumes:
  sqlite_data:
    driver: local

networks:
  app_network:
    driver: bridge